Adicionar payer save adapter
anamilchert/Mini-Asaas pull request #27
Opened 2024-05-24 15:41 UTC by jgabrielbmm

### Impacto
Criando um Adapter para para o método de salvar um Payer (Pagador), além disso foi acrescentado o @GrailsCompileStatic no PayerService e no PayerSaveAdapter e por fim na validação foi feito uso do addError que vem do DomainUtils.

### Release Note (Descrição que irá no forno)

### PR Predecessora: 

### Plano de deploy:
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA: https://asaas-team-ytm2rk8u.atlassian.net/jira/software/projects/KAN/boards/1?selectedIssue=KAN-49

### Link dos mockups

### Prints do desenvolvimento

2024-05-24 20:54 UTC, millenadias commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +    def payerService
```suggestion
    PayerService payerService
```

2024-05-24 20:54 UTC, millenadias commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        [customers: customers]
```suggestion
        return [customers: customers]
```

2024-05-24 20:54 UTC, millenadias commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        List<Customer> customers = Customer.list()
em qual cenário isso vai ser usado? pensando no uso futuro, o customer vai logar, pq ele veria uma listagem de Customers? E pq isso estaria numa controller voltada pro Payer?

2024-05-24 20:54 UTC, millenadias commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +
Linha em branco no final de bloco assim é desnecessária, se for entre regras para separar blocos de regras, tudo bem
```suggestion
```

2024-05-24 20:54 UTC, millenadias commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        if (payer) {
usa earlyReturn pra casos assim
```suggestion
        if (payer) return [payer: payer]
```

2024-05-24 20:54 UTC, millenadias commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        if (!payerSaveAdapter.customerId) {
isso aqui no meio das demais validações, aparecerá em tela pra usuário. Isso de fato é algo que o cliente deve ver? Não é um problema técnico?
Sendo técnico, sugiro tratar pra nem chegar, já lançar exception antes

2024-05-24 20:54 UTC, millenadias commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        if (!payerSaveAdapter.street || !payerSaveAdapter.number ||
a leitura disso tende a ficar complicada. Cria um método que te retorne se o endereço está incompleto e cada linha faz o if, pra facilitar o entendimento. Nome do método poderia ser algo como hasIncompleteAddress, retornando um boolean

![image](https://github.com/anamilchert/Mini-Asaas/assets/48190885/d9aada8b-56e0-4733-a6cc-34629f2d08a8)

2024-05-27 11:22 UTC, jgabrielbmm commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        List<Customer> customers = Customer.list()
Esse busca de customer no index é apenas temporaria para os teste de criação de payer, depois será removido. 
Uma task para remoção foi criada.

2024-05-27 11:52 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        if (!payerSaveAdapter.customerId) {
Adicionei um RuntimeException quando o customerId é null

2024-05-27 23:25 UTC, kmurilo commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        List<Customer> customers = Customer.list()
Este list vai trazer todos os customers certo? 
E se quisermos trazer apenas os não deletados?

2024-05-27 23:25 UTC, kmurilo commented on Asaas/src/main/groovy/asaas/adapter/PayerSaveAdapter.groovy
> +    String CEP
Para nomes de variáveis sempre temos que começar com letras minusculas.

Mas além disso cep é o nome brasileiro "código de endereçamento postal". Vamos manter tudo em inglês no caso o correto é postalCode.

2024-05-27 23:25 UTC, kmurilo commented on Asaas/src/main/groovy/asaas/adapter/PayerSaveAdapter.groovy
> +    String neighborhood
Esse campo é para representar o bairro? Se sim, aqui no asaas, usamos province

2024-05-28 11:17 UTC, jgabrielbmm commented on Asaas/src/main/groovy/asaas/adapter/PayerSaveAdapter.groovy
> +    String neighborhood
é para representar o bairro, vou colocar um task para fazer essa alteração

2024-05-28 11:18 UTC, jgabrielbmm commented on Asaas/src/main/groovy/asaas/adapter/PayerSaveAdapter.groovy
> +    String CEP
a gente tem um task para trocar o cep para zipCode, mas você prefere zipCode ou postalCode ?

2024-05-28 11:21 UTC, jgabrielbmm commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        List<Customer> customers = Customer.list()
Essa lista vai sumir, ela foi coloca apenas para ajudar na criação de payer enquanto não temos uma forma de autenticação para saber qual customer está usando o sistema

2024-05-31 12:38 UTC, kmurilo commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        return [customers: customers]
Dificilmente usamos nomes de váriaveis no plural. Nosso padrão é usar o sufixo list. Nesta caso ficaria customerList

2024-05-31 12:38 UTC, kmurilo commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        } catch (ValidationException e) {
```suggestion
        } catch (ValidationException validationException) {
```

2024-05-31 12:38 UTC, kmurilo commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        } catch (RuntimeException e) {
```suggestion
        } catch (RuntimeException runtimeException) {
```

2024-05-31 12:38 UTC, kmurilo commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        try {
Ainda faltou tratar a Exception

2024-05-31 12:38 UTC, kmurilo commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        if (payer) return [payer: payer]
Acho interessante achar um padrão para vocês tratarem estes casos, vi que a Ana fez de uma forma e vc de outra.

2024-05-31 12:38 UTC, kmurilo commented on Asaas/grails-app/services/asaas/PayerService.groovy
>      public List<Payer> list(Long customerId) {
Podemos explicitar no nome desse método que ele é um listByCustomer.

2024-05-31 12:38 UTC, kmurilo commented on Asaas/src/main/groovy/asaas/adapter/PayerSaveAdapter.groovy
> +    String CEP
acho que postalCode fica mais genérico

2024-05-31 12:38 UTC, kmurilo commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private static Boolean hasIncompleteAddress(PayerSaveAdapter payerSaveAdapter) {
Customer tambem tem endereço? 
De qualquer forma isso poderia ir para uma classe onde só trate coisas de endereço

2024-05-31 12:38 UTC, kmurilo commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private Payer validationSave(PayerSaveAdapter payerSaveAdapter) {
Os métodos devem sempre começar com um verbo, Nesse casos o correto seria validateSave()

2024-05-31 13:44 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private Payer validationSave(PayerSaveAdapter payerSaveAdapter) {
troquei

2024-05-31 13:44 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private static Boolean hasIncompleteAddress(PayerSaveAdapter payerSaveAdapter) {
Tem um task para fazer a separação, só vou conversar com a ana para ver qual a melhor forma

2024-05-31 13:49 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
>      public List<Payer> list(Long customerId) {
troquei para listByCustomer

2024-05-31 13:57 UTC, jgabrielbmm commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        try {
adicionado

2024-05-31 13:57 UTC, jgabrielbmm commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        if (payer) return [payer: payer]
Eu e ana vamos definir um padrão

2024-06-03 13:12 UTC, Yuri-Ferrari requested changes

2024-06-03 13:12 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/PayerService.groovy
>      }
Não é necessário criar método pra isto pois não contém regra de negócio, pode chamar a query do Repository no local onde esse método é chamado

2024-06-03 13:12 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        if (!payerSaveAdapter.personType) DomainUtils.addError(payer, "Tipo de pessoa inválido")
O erro fala que é inválido, mas a validação apenas valida se o valor não é nulo e não se um valor é válido

2024-06-03 13:12 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private static Boolean hasIncompleteAddress(PayerSaveAdapter payerSaveAdapter) {
Sugiro inverter a lógica, mudando o nome do método pra 'hasValidAddress', fica mais fácil o entendimento, pois tu não precisa pensar no inverso

2024-06-03 14:08 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private static Boolean hasIncompleteAddress(PayerSaveAdapter payerSaveAdapter) {
trocado

2024-06-03 14:44 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
>      }
Troca feita

2024-06-04 11:06 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        if (!payerSaveAdapter.personType) DomainUtils.addError(payer, "Tipo de pessoa inválido")
separei em duas validações uma que ver se é null e outra que ver se o tipo tá errado

2024-06-05 12:27 UTC, Yuri-Ferrari requested changes

2024-06-05 12:27 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        if (!payerSaveAdapter.street) return true
Se não tem rua deveria retornar false pro nome do método fazer sentido, mesmo comentário pras validações abaixo

2024-06-05 12:48 UTC, anamilchert approved these changes

2024-06-05 21:06 UTC, Yuri-Ferrari approved these changes

2024-06-05 21:06 UTC, merged