Fluxo de payer update
anamilchert/Mini-Asaas pull request #29
Opened 2024-05-28 15:16 UTC by jgabrielbmm

### Impacto
Criando o fluxo de atualização de um Payer com o envio de feedback do backend para o frontend nos casos de sucessos e errors. Além disso, troquei o validationAddress para DomainUtils para que ele possa ser usado em outros locais onde precise da validação de Address

### Release Note (Descrição que irá no forno)

### PR Predecessora: https://github.com/anamilchert/Mini-Asaas/pull/27

### Plano de deploy:
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA: https://asaas-team-ytm2rk8u.atlassian.net/jira/software/projects/KAN/boards/1?selectedIssue=KAN-38

### Link dos mockups

### Prints do desenvolvimento

2024-05-29 13:21 UTC, kmurilo commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        } catch (RuntimeException e) {
Precisa tratar os outros tipos de exception aqui tbm

2024-05-29 13:21 UTC, kmurilo commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        if (validatedPayer.hasErrors()) throw new ValidationException("Erro ao atualizar um pagador", validatedPayer.errors)
```suggestion
        Payer validatedPayer = validationUpdate(payerUpdateAdapter)
        if (validatedPayer.hasErrors()) throw new ValidationException("Erro ao atualizar um pagador", validatedPayer.errors)
```

2024-05-29 13:21 UTC, kmurilo commented on Asaas/src/main/groovy/asaas/utils/DomainUtils.groovy
> +    public static Boolean hasIncompleteAddress(AddressAdapter addressAdapter) {
Domain Utils não é o local correto para essa validação.

2024-05-29 17:18 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        if (validatedPayer.hasErrors()) throw new ValidationException("Erro ao atualizar um pagador", validatedPayer.errors)
corrigi

2024-05-29 17:18 UTC, jgabrielbmm commented on Asaas/grails-app/controllers/asaas/PayerController.groovy
> +        } catch (RuntimeException e) {
adicionei novos catches

2024-05-31 12:54 UTC, kmurilo commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        payer.name = payerAdapter.name
Chegou a ver se conseguimos aproveitar coisas que estão sendo feitas em comum no update e no save para unificar?

2024-05-31 12:54 UTC, kmurilo commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private Payer validate(PayerAdapter payerAdapter, Boolean update = false) {
Não costumamos usar default parameter. Tem mesmo a necessidade de informar aqui se é um update ou não?

2024-05-31 12:54 UTC, kmurilo commented on Asaas/src/main/groovy/asaas/utils/DomainUtils.groovy
> +import asaas.adapter.AddressAdapter
Por que esse import aqui?

2024-05-31 13:01 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +        payer.name = payerAdapter.name
Sim eu até pensei em uma forma, mas teria que usar params com valor default

2024-05-31 13:02 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private Payer validate(PayerAdapter payerAdapter, Boolean update = false) {
Eu consigo fazer sem usar valor default, porem eu teria que setar alguns valores no payerAdapter que está faltando para que a validação funcione.

2024-05-31 13:02 UTC, jgabrielbmm commented on Asaas/src/main/groovy/asaas/utils/DomainUtils.groovy
> +import asaas.adapter.AddressAdapter
Esse eu esqueci de remover

2024-05-31 13:11 UTC, jgabrielbmm commented on Asaas/src/main/groovy/asaas/utils/DomainUtils.groovy
> +import asaas.adapter.AddressAdapter
removido

2024-06-03 13:18 UTC, Yuri-Ferrari requested changes

2024-06-03 13:18 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/PayerService.groovy
> +    private Payer validate(PayerAdapter payerAdapter, Boolean update = false) {
Nesse caso sempre passe o parâmetro e retire o default.

2024-06-04 11:16 UTC, Yuri-Ferrari approved these changes

2024-06-05 12:50 UTC, anamilchert approved these changes

2024-06-05 21:09 UTC, Yuri-Ferrari commented
Conflitos

2024-06-06 15:06 UTC, merged