Fluxo listar obter payment
anamilchert/Mini-Asaas pull request #30
Opened 2024-05-29 16:00 UTC by jgabrielbmm

### Impacto

### Release Note (Descrição que irá no forno)
Adicionando métodos de buscas de Payment de acordo com ID, cusomerId e payerId usando agora o Repository 

### PR Predecessora

### Plano de deploy:
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA: https://asaas-team-ytm2rk8u.atlassian.net/jira/software/projects/KAN/boards/1?selectedIssue=KAN-41

### Link dos mockups

### Prints do desenvolvimento

2024-06-03 13:06 UTC, Yuri-Ferrari requested changes

2024-06-03 13:06 UTC, Yuri-Ferrari commented on Asaas/grails-app/controllers/asaas/PaymentController.groovy
> +    PayerService payerService
Podem deixar como def, não é necessário tipar explicitamente

2024-06-03 13:06 UTC, Yuri-Ferrari commented on Asaas/grails-app/controllers/asaas/PaymentController.groovy
> +            flash.message = "Houve um error inesperado ao tentar salvar uma cobrança. Por favor, tente novamente"
```suggestion
            flash.message = "Houve um erro inesperado ao tentar salvar uma cobrança. Por favor, tente novamente"
```

2024-06-03 13:06 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/PaymentService.groovy
> +    }
Não precisa de método pra esses casos pois não tem regra de negócio associada, podem chamar a query do Repository diretamente nos locais que o método está sendo chamado

2024-06-03 13:06 UTC, Yuri-Ferrari commented on Asaas/grails-app/views/templates/_paymentList.gsp
> +         <div>-------------------------</div>
Por que isso é necessário?

2024-06-03 13:12 UTC, jgabrielbmm commented on Asaas/grails-app/views/templates/_paymentList.gsp
> +         <div>-------------------------</div>
Como não tamos fazendo testes unitário e testes de integração, a gente tá criando algumas telas básicas só testes dos services .

2024-06-03 13:14 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PaymentService.groovy
> +    }
Certo, eu só criei eles no services por que achava que não deveria chamar o Repository no Controller

2024-06-03 13:21 UTC, jgabrielbmm commented on Asaas/grails-app/controllers/asaas/PaymentController.groovy
> +            flash.message = "Houve um error inesperado ao tentar salvar uma cobrança. Por favor, tente novamente"
corrigido

2024-06-03 13:43 UTC, jgabrielbmm commented on Asaas/grails-app/services/asaas/PaymentService.groovy
> +    }
Fiz a mudança de local

2024-06-04 11:01 UTC, Yuri-Ferrari commented on Asaas/grails-app/views/templates/_paymentList.gsp
> +         <div>-------------------------</div>
Conforme conversado, remover o tracejado

2024-06-04 11:33 UTC, jgabrielbmm commented on Asaas/grails-app/views/templates/_paymentList.gsp
> +         <div>-------------------------</div>
Removido

2024-06-05 12:15 UTC, Yuri-Ferrari approved these changes

2024-06-05 12:16 UTC, merged