Fluxo edit payment
anamilchert/Mini-Asaas pull request #34
Opened 2024-06-04 12:55 UTC by jgabrielbmm

### Impacto
Adicionei um método para atualizar uma cobrança caso ela esteja como PENDING, além disso eu adicionei o @GrailsCompileStatic no PaymentAdapter e fiz uma mudança no formato do form da página de show para que seja possível editar apenas alguns campos desse formulario.

### Release Note (Descrição que irá no forno)

### PR Predecessora: https://github.com/anamilchert/Mini-Asaas/pull/30

### Plano de deploy:
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA: https://asaas-team-ytm2rk8u.atlassian.net/jira/software/projects/KAN/boards/1?selectedIssue=KAN-59

### Link dos mockups

### Prints do desenvolvimento

2024-06-05 12:24 UTC, Yuri-Ferrari requested changes

2024-06-05 12:24 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/PaymentService.groovy
> +        if (!paymentAdapter.dueDate) DomainUtils.addError(payment, "Informe um valor válido")
Mensagem errada

2024-06-05 12:24 UTC, Yuri-Ferrari commented on Asaas/grails-app/views/payment/show.gsp
> +            <input type="text" id="customer" name="customerId" value="${payment?.customer.id}" readonly>
Não deveria existir a possibilidade do Payment ser nulo na visualização

2024-06-05 12:24 UTC, Yuri-Ferrari commented on Asaas/src/main/groovy/asaas/adapter/PaymentAdapter.groovy
> +  Integer value
Deverá ser aceito valores decimais

2024-06-05 15:43 UTC, anamilchert approved these changes

2024-06-05 21:11 UTC, Yuri-Ferrari requested changes

2024-06-05 21:11 UTC, Yuri-Ferrari commented on Asaas/grails-app/views/payment/show.gsp
> +            <input type="date" id="dueDate" name="dueDate" value="${date.formatDate(date: payment?.dueDate)}">
Sobrou 2 elvisOperator

2024-06-05 21:11 UTC, Yuri-Ferrari commented on Asaas/src/main/groovy/asaas/adapter/PaymentAdapter.groovy
> +    this.value = CurrencyUtils.fromStringToInteger(params.value as String)
Como mudou o tipo da variável precisa de outro método de conversão

2024-06-06 14:22 UTC, Yuri-Ferrari approved these changes
Conflitos

2024-06-06 15:04 UTC, merged