Criando customer adapter
anamilchert/Mini-Asaas pull request #35
Opened 2024-06-06 14:47 UTC by anamilchert

### Impacto

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy:
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA
https://asaas-team-ytm2rk8u.atlassian.net/jira/software/projects/KAN/boards/1?selectedIssue=KAN-53

### Link dos mockups

### Prints do desenvolvimento

2024-06-06 15:15 UTC, Yuri-Ferrari requested changes

2024-06-06 15:15 UTC, Yuri-Ferrari commented on Asaas/grails-app/controllers/asaas/CustomerController.groovy
> +                render(view: "show", model: [customer: new Customer(params)])
Se deu um erro deveria voltar pra tela de criação que o cliente estava com os dados preenchidos, não pode mandar pro show pois lá é a tela que mostra os dados de um cliente salvo e se deu erro no salvamento, não tem cliente salvo pra mostrar

2024-06-06 15:15 UTC, Yuri-Ferrari commented on Asaas/grails-app/controllers/asaas/CustomerController.groovy
> +                    render(view: 'show', model: [customer: Customer.get(id)])
Aqui deveria voltar pra tela de edição, pois o cliente estava editando, não visualizando o mesmo

2024-06-06 15:15 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/CustomerService.groovy
> +            !customerAdapter.city || !customerAdapter.state || !customerAdapter.zipCode) {
IF muito extenso é ruim de ler e pode gerar problema de manutenção no futuro, crie um método para essas validações e utilize earlyReturn

2024-06-06 15:15 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/CustomerService.groovy
>          }
Foge do escopo do PR, que é criar adapter, mas agora que tem validação de CNPJ e CPF, apliquem ela aqui e em outros pontos

2024-06-06 15:15 UTC, Yuri-Ferrari commented on Asaas/grails-app/services/asaas/CustomerService.groovy
> +            customer.address.zipCode = adapter.zipCode ?: customer.address.zipCode
Se é obrigatório informar todos os dados pra fazer o update do Customer, não é necessário validar se eles existem e se não existirem usar o dado do Customer. Traduzindo, atribui as props que estão no adapter e não usa o ?: 
Identações diferentes, mantenha sempre a mesma pra ajudar na leitura.

2024-06-06 15:15 UTC, Yuri-Ferrari commented on Asaas/grails-app/views/customer/edit.gsp
> +            <g:textField name="zipCode" value="${customer?.address?.zipCode}" class="form-control" required=""/>
Essa é uma tela de edição de cliente, logo o cliente tem que existir pra essa tela ser chamada, além disso endereço é obrigatório então não precisa de nenhum elvisOperator

2024-06-12 13:12 UTC, welingtonloh commented
@anamilchert coloca em impacto um breve resumo do que esse PR faz. O template dos PRs precisa ser utilizado

2024-06-12 13:22 UTC, welingtonloh commented on Asaas/grails-app/controllers/asaas/CustomerController.groovy
>                  } catch (ValidationException e) {
Arruma essa indentação já nesse PR, o catch está bem deslocado

E não abreviem, utilizem:
} catch (ValidationException validationException) {

2024-06-12 13:22 UTC, welingtonloh commented on Asaas/grails-app/services/asaas/CustomerService.groovy
> +        Customer customerValues = validateCustomerParams(customerAdapter)
```suggestion
        Customer validatedCustomer = validateSave(customerAdapter)
```

2024-06-12 13:22 UTC, welingtonloh commented on Asaas/grails-app/services/asaas/CustomerService.groovy
> +        validateCpfCnpj(adapter.cpfCnpj)
o update e o save deveriam ter validações muito parecidas, pq validamos somente cpfCnpj no update?

2024-06-12 13:22 UTC, welingtonloh commented on Asaas/grails-app/services/asaas/CustomerService.groovy
> +        if (!customerAdapter.email) {
Uma linha em branco entre os ifs, por organização

Não é validado se é um email válido no backend?
Não é validado se é um cpfCnpj válido?
Isso é bem importante, sugiro que já registrem a tarefa e vejam em seguida

É importante tbm validar estado, validar telefone, validar CEP

2024-06-12 13:22 UTC, welingtonloh commented on Asaas/grails-app/services/asaas/CustomerService.groovy
> +        if (!customerAdapter.number) {
Linha em branco entre os ifs, por organização

2024-06-12 13:22 UTC, welingtonloh commented on Asaas/grails-app/services/asaas/CustomerService.groovy
> +        if (!customerAdapter.state) {
Registrem tarefa para criarmos uma Enum de estados

Para selecionar em tela um dos estados e validar no backend se foi informado um estado válido

2024-06-12 15:46 UTC, anamilchert commented on Asaas/grails-app/services/asaas/CustomerService.groovy
> +        validateCpfCnpj(adapter.cpfCnpj)
Porque as informações de nome, email e personType não podem ser alteradas, apenas as informações de endereço. O cpfCnpj realmente não precisa ser validado ai

2024-06-13 17:29 UTC, welingtonloh requested changes

2024-06-13 17:29 UTC, welingtonloh commented on Asaas/grails-app/controllers/asaas/CustomerController.groovy
> +            redirect(action: 'show', id: customer.id)
indentação estranha ainda

2024-06-14 11:40 UTC, welingtonloh commented on Asaas/grails-app/controllers/asaas/CustomerController.groovy
> +            String errorsMessage = e.errors.allErrors.collect { it.defaultMessage }.join(', ')
Isso foi testado? e.errors ainda funciona?

2024-06-14 11:40 UTC, welingtonloh commented on Asaas/grails-app/controllers/asaas/CustomerController.groovy
> +
Remover linhas sobrando

2024-06-14 11:40 UTC, welingtonloh commented on Asaas/grails-app/controllers/asaas/CustomerController.groovy
> +            String errorsMessage = e.errors.allErrors.collect { it.defaultMessage }.join(', ')
```suggestion
        } catch (ValidationException validationException) {
            String errorsMessage = validationException.errors.allErrors.collect { it.defaultMessage }.join(', ')
```
Quando solicitamos ajustes, validar o PR todo se tem codigo parecido para ajustar

2024-06-14 15:10 UTC, welingtonloh approved these changes

2024-06-14 15:10 UTC, merged